package com.srp.datamindAi.model;

import java.util.List;

/**
 * ChartData model representing chart configuration and data for dashboard visualization.
 * Supports multiple chart types: bar, line, pie, doughnut, and summary.
 * 
 * Follows accessibility standards (WCAG 2.1) with clear labels and descriptions.
 * 
 * @author DataMind AI Backend Team
 * @version 2.0
 */
public class ChartData {

    // Chart type: bar, line, pie, doughnut, or summary
    private String type;
    
    // Human-readable chart title for accessibility
    private String title;
    
    // X-axis or category labels (clear, descriptive names)
    private List<String> labels;
    
    // Dataset configurations with labels (supports multiple series)
    private List<DatasetConfig> datasets;
    
    // Summary/insight text (generated by AI or backend logic)
    private String insight;

    public ChartData() {
    }

    /**
     * Constructor for creating chart data with comprehensive configuration.
     * 
     * @param chartType The type of chart (bar, line, pie, doughnut, summary)
     * @param title Human-readable chart title
     * @param labels Category labels for X-axis or legend
     * @param datasets List of dataset configurations
     * @param insight Professional insight text (2-sentence summary)
     */
    public ChartData(String type, String title, List<String> labels, 
                    List<DatasetConfig> datasets, String insight) {
        this.type = type;
        this.title = title;
        this.labels = labels;
        this.datasets = datasets;
        this.insight = insight;
    }

    // ============== Getters and Setters ==============

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public List<String> getLabels() {
        return labels;
    }

    public void setLabels(List<String> labels) {
        this.labels = labels;
    }

    public List<DatasetConfig> getDatasets() {
        return datasets;
    }

    public void setDatasets(List<DatasetConfig> datasets) {
        this.datasets = datasets;
    }

    public String getInsight() {
        return insight;
    }

    public void setInsight(String insight) {
        this.insight = insight;
    }

    // ============== Backward Compatibility (Deprecated) ==============
    
    /**
     * @deprecated Use getChartType() instead
     */
    @Deprecated
    public String getChartType() {
        return type;
    }

    /**
     * @deprecated Use setType() instead
     */
    @Deprecated
    public void setChartType(String chartType) {
        this.type = chartType;
    }

    /**
     * @deprecated Use getDatasets() instead
     */
    @Deprecated
    public List<Integer> getDataset() {
        // Convert DatasetConfig back to integers for backward compatibility
        if (datasets != null && !datasets.isEmpty()) {
            return datasets.get(0).getData();
        }
        return null;
    }

    /**
     * @deprecated Use getSummary() instead
     */
    @Deprecated
    public String getSummary() {
        return insight;
    }

    /**
     * @deprecated Use setInsight() instead
     */
    @Deprecated
    public void setSummary(String summary) {
        this.insight = summary;
    }

    /**
     * Inner class representing a single dataset with label and data.
     * Supports accessibility by including descriptive labels.
     */
    public static class DatasetConfig {
        private String label;
        private List<Integer> data;

        public DatasetConfig() {
        }

        public DatasetConfig(String label, List<Integer> data) {
            this.label = label;
            this.data = data;
        }

        public String getLabel() {
            return label;
        }

        public void setLabel(String label) {
            this.label = label;
        }

        public List<Integer> getData() {
            return data;
        }

        public void setData(List<Integer> data) {
            this.data = data;
        }
    }
}
